export enum JobTitle {

    PROJECT_MANAGER = "PROJECT_MANAGER",
    TEAM_LEAD = "TEAM_LEAD",
    BACKEND_DEVELOPER = "BACKEND_DEVELOPER",
    FRONTEND_DEVELOPER = "FRONTEND_DEVELOPER",
    FULLSTACK_DEVELOPER = "FULLSTACK_DEVELOPER",
    MOBILE_DEVELOPER = "MOBILE_DEVELOPER",
    QA_ENGINEER = "QA_ENGINEER",
    DEVOPS_ENGINEER = "DEVOPS_ENGINEER",
    BUSINESS_ANALYST = "BUSINESS_ANALYST",
    INTERN = "INTERN"
}