export enum JobTitle {

    PROJECT_MANAGER,
    TEAM_LEAD,
    BACKEND_DEVELOPER,
    FRONTEND_DEVELOPER,
    FULLSTACK_DEVELOPER,
    MOBILE_DEVELOPER,
    QA_ENGINEER,
    DEVOPS_ENGINEER,
    BUSINESS_ANALYST,
    INTERN
}